// Albumes
export const ACTUALIZAR_ALBUMES = 'ACTUALIZAR_ALBUMES';
export const ACTUALIZAR_SELECTED_ALBUM = 'ACTUALIZAR_SELECTED_ALBUM';

// Photos
export const ACTUALIZAR_PHOTOS = 'ACTUALIZAR_PHOTOS';
